CREATE TABLE IF NOT EXISTS materials (
  id INT AUTO_INCREMENT PRIMARY KEY,
  barcode VARCHAR(100) NOT NULL UNIQUE,
  material_name VARCHAR(255) NOT NULL,
  quantity DECIMAL(10, 2) NOT NULL,
  threshold_limit DECIMAL(10, 2) DEFAULT 10.00,
  unit VARCHAR(50) DEFAULT 'kg',
  batch_number VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
