services:
  - type: web
    name: inventory-backend
    env: node
    plan: free
    buildCommand: "npm install && npx prisma generate"
    startCommand: "npm run server"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
