import os
import json
from ai_training.config import FEATURE_REGISTRY_JSON, FEATURE_IMPORTANCE_TEMPLATE_JSON


class FeatureLoader:
    """
    FeatureLoader
    ─────────────
    Reads feature metadata schemas and central registry definitions
    generated by RM Monitor.
    """

    def load_feature_registry(self) -> dict:
        if not os.path.exists(FEATURE_REGISTRY_JSON):
            return {}
        with open(FEATURE_REGISTRY_JSON, "r", encoding="utf-8") as f:
            return json.load(f)

    def load_importance_template(self) -> dict:
        if not os.path.exists(FEATURE_IMPORTANCE_TEMPLATE_JSON):
            return {}
        with open(FEATURE_IMPORTANCE_TEMPLATE_JSON, "r", encoding="utf-8") as f:
            return json.load(f)


__all__ = ["FeatureLoader"]
